### ISSUE TITLE
Error: Unhandled exception executing command

### ISSUE THREAD

**Issue by ghost** [drtshock/Factions#1139] opened 2018-03-28 17:14 UTC
FactionsUUID: Factions v1.6.9.5-U0.2.2-b112

Server software: Paper version git-Paper-1363 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

Error: https://hastebin.com/azumohehid.vbs

Thanks to fix this error.

**Comment by dariasc** [comment] 2018-03-28 17:15
Duplicate of #1128

**Comment by drtshock** [comment] 2018-03-29 06:39
Fixed in latest release.

**Closed as completed by drtshock** 2018-03-29 06:39 UTC
