### ISSUE TITLE
Server locking on autosave for 3 seconds

### ISSUE THREAD

**Issue by TitanicFreak** [drtshock/Factions#43] opened 2014-08-12 19:03 UTC
Was requested to open this drtshock himself.

Basically the server locks up  entirely for 3 seconds on auto save. I've resorted to making the auto save every few years and making it save on stop at the moment. Causes some problems naturally for unstable servers.

Timings: http://aikar.co/timings.php?url=8028973
Main thing in the timings in question: http://i.imgur.com/zvSnBgE.png
Factions UUID Build #: 48 (1.6.9.5-U0.1.3)
Spigot build #: 1596

**Comment by drtshock** [comment] 2014-08-12 21:24
Also a duplicate of #42

**Comment by hintss** [comment] 2014-10-15 06:04
it _looks_ like saving is synchronous, so if you have a ton of stuff to save...  

*disclaimer: I'm probably being an idiot here

**Closed as completed** 2014-11-05 17:37 UTC
Labels: bug, duplicate, enhancement
