### ISSUE TITLE
Faction chat not compatible with ChatControl

### ISSUE THREAD

**Issue by Kira07** [drtshock/Factions#556] opened 2015-11-10 17:56 UTC
The factionchat isn't compatible with chatcontrol and of course, since FactionsUUID isn't free, chatcontrol dev won't make it compatible. Could you please do something about this ? Chatcontrol doesn't have any effect in faction chat..

**Comment by random1167** [comment] 2015-11-28 01:00
bump XD

**Comment by drtshock** [comment] 2015-11-30 16:47
This plugin is open source. Not sure what the issue is though. Saying 'not compatible' doesn't help :\

**Comment by Kira07** [comment] 2015-11-30 17:01
The chatcontrol filter system does not apply to the faction chat :/

2015-11-30 16:47 GMT+00:00 Trent Hensler notifications@github.com:

**Comment by drtshock** [comment] 2015-11-30 20:46
Oh actually, I see why.

Issue is that instead of modifying recipients, event is cancelled and message is sent manually. This needs to be fixed.

**Comment by Kira07** [comment] 2015-11-30 22:24
So you will be able to fix this ? Great news, thank you

2015-11-30 20:46 GMT+00:00 Trent Hensler notifications@github.com:

**Comment by CmdrKittens** [comment] 2019-07-10 02:44
I am closing this issue due to its age with the assumption it is no longer a problem. If you encounter this problem, or a similar problem, please create a new issue for it.

**Closed as completed by CmdrKittens** 2019-07-10 02:44 UTC
Labels: bug
