### ISSUE TITLE
/f show error

### ISSUE THREAD

**Issue by CakeRage** [drtshock/Factions#491] opened 2015-08-02 20:17 UTC
http://pastebin.com/eyc2b9B0
I keep getting that whenever someone does /f show, any fix?

**Comment by juIio** [comment] 2015-08-05 00:54
Is that the full error? You should also post your config.

**Comment by drtshock** [comment] 2015-08-06 16:40
That's not the full error. Can you paste your mc version as well.

**Comment by drtshock** [comment] 2015-08-06 22:02
Duplicate of https://github.com/drtshock/Factions/issues/489

**Closed as completed by drtshock** 2015-08-06 22:02 UTC
