### ISSUE TITLE
/f t balance Crashing Server

### ISSUE THREAD

**Issue by kjh16** [drtshock/Factions#579] opened 2015-12-07 20:46 UTC
Major issue, this crashes the server everytime the /f top | /f t command is ran with the balance parameter. Here is an example error: 

http://hastebin.com/aradomerib.avrasm

**Comment by kjh16** [comment] 2015-12-07 20:48
I saw there was an additional thing on this, but I'm not sure if there is a way to revoke only say factions.top.balance yet. If there is, please let me know. Thanks!

**Comment by drtshock** [comment] 2015-12-10 17:39
Interesting, which build are you on?

**Comment by kjh16** [comment] 2015-12-10 19:01
The latest, I'm not sure of the exact version. 

Another server owner (one in competition to mine) came on and started spamming it. It's basically a bugged backend to using essentials baltop, which as we all know, is terriblely maintained.

**Comment by drtshock** [comment] 2015-12-10 19:51
Type /f version and give the **exact** output.

**Comment by kjh16** [comment] 2015-12-10 22:28
v1.6.9.5-U0.1.18-b298
http://prntscr.com/9cplx6

**Comment by kjh16** [comment] 2015-12-12 14:16
Another example crash: 
http://pastebin.com/BKKu0dKJ

**Comment by bob7l** [comment] 2015-12-17 20:14
Your factions depends on Essentials economy, which stores all the economy data in YAML format along with the rest of the players info. Soo checking the balance of all the factions FORCES essentials to load the separate YAML files containing each factions money on the same thread as whatever invoked the method which will most likely crash the server because of the massive delay from loading files. Or in other words: This isn't an easily fixable problem. Especially since even if he ran the top operation in another thread, it'd still be a heavy operation and would more then likely be incredibly un-thread safe. 

The only solution i can think of atm would be to throw away 3rd party economy dependencies for factions (not players) and instead save/load it directly from where ever you have the factions saved. 

Or just completely remove the /f top command lol

**Comment by Kakifrucht** [comment] 2015-12-17 21:34
Actually, afaik Essentials data can be accessed async. I have written a little scripts which iterates over every home and prints all homes that are in a given radius. Seems to work without issues, so I just suppose Essentials data management was designed to be thread safe.

**Comment by bob7l** [comment] 2015-12-18 00:27
Whether it's "thread-safe" or not, he still has to have support for every other economy plugin aswell. And even if every economy plugin compatible with vault is thread-safe, it'd still be bad to constantly open new threads and iterate over thousands of entries on the disk every time someone types the command.

**Comment by Kakifrucht** [comment] 2015-12-18 02:20
Yeah, that's right, just wanted to point that out.

**Comment by CmdrKittens** [comment] 2019-07-10 02:43
I am closing this issue due to its age with the assumption it is no longer a problem. If you encounter this problem, or a similar problem, please create a new issue for it.

**Closed as completed by CmdrKittens** 2019-07-10 02:43 UTC
