### ISSUE TITLE
issue on 1.11

### ISSUE THREAD

**Issue by Mineacer** [drtshock/Factions#885] opened 2017-01-07 04:11 UTC
http://pastebin.com/z8Yq26rP

**Comment by Mineacer** [comment] 2017-01-09 02:01
Anyone know how to fix this?

**Comment by Kakifrucht** [comment] 2017-01-09 02:25
Wait for update.

**Comment by Mineacer** [comment] 2017-01-09 04:44
Okay, waiting thanks brother.

**Comment by drtshock** [comment] 2017-01-13 16:55
Can you give me your server version? The method is there, just deprecated https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/entity/EntityDamageByEntityEvent.html

**Comment by drtshock** [comment] 2017-01-13 16:56
Duplicate of #883

**Closed as completed by drtshock** 2017-01-13 16:56 UTC
