### ISSUE TITLE
Players can't sethome in wilderness

### ISSUE THREAD

**Issue by owensto** [drtshock/Factions#569] opened 2015-11-29 18:35 UTC
The plugin recognizes wilderness as neutral territory however I want to make it so players can't sethome in faction territory that they're either neutral or enemies with. They aren't able to sethome in wilderness now though because it's considered "neutral" territory.  If there's a way to fix this so players can set their homes in wilderness but not a faction's neutral territory I'd love to know.

**Comment by Gardiac** [comment] 2015-12-07 20:39
Go to "conf.json" and search for something like "HomeMustBeInClaimed" you should found it I cant remember exactly...

**Comment by drtshock** [comment] 2016-01-03 19:39
Duplicate of https://github.com/drtshock/Factions/issues/590

**Closed as completed by drtshock** 2016-01-03 19:39 UTC
