### ISSUE TITLE
Faction name Tag in NICK

### ISSUE THREAD

**Issue by Vukajlovic** [drtshock/Factions#393] opened 2015-05-21 18:53 UTC
I will ask you again but now I have pictures
This is on 14 version of plugin picture
![fr](https://cloud.githubusercontent.com/assets/12477841/7756392/2d7f58a0-fffb-11e4-97be-4f995551715c.png)
When I update on last version , I haven't now this tag!
![2015-05-21_20 45 40](https://cloud.githubusercontent.com/assets/12477841/7756410/5c2b22b0-fffb-11e4-8ba5-4bc94bc0403c.png)

I said I haven't error

**Comment by drtshock** [comment] 2015-05-26 00:21
Duplicate of https://github.com/drtshock/Factions/issues/390 and still doesn't have ANY OF THE INFORMATION WE NEED TO HELP YOU.

**Closed as completed by drtshock** 2015-05-26 00:21 UTC
