### ISSUE TITLE
/f home and message changes

### ISSUE THREAD

**Issue by christiaanbruijnes** [drtshock/Factions#14] opened 2014-06-02 16:36 UTC
I am using the plugin SkyWars, when your in a game all commands are blocked automaticly except the /f command. Is there any way to fix this bug?

As secondly, It would be amazing if you can make some message changes.

**Comment by drtshock** [comment] 2014-06-30 18:34
Duplicate of https://github.com/drtshock/Factions/issues/22 We'll keep discussion on that one.

**Closed as completed by drtshock** 2014-06-30 18:35 UTC
