### ISSUE TITLE
Neutral Territory Sethome

### ISSUE THREAD

**Issue by owensto** [drtshock/Factions#559] opened 2015-11-15 20:10 UTC
So I try to make it so you can't set home in a faction's neutral territory, but for some reason this disabled setting homes in wilderness too.  I just want it so people can't /sethome in a neutral faction's territory, but they can set home anywhere in wilderness.

**Comment by owensto** [comment] 2015-11-18 01:07
Still having this issue with no clue how to fix.

**Comment by owensto** [comment] 2015-11-22 02:48
Still having this issue... Not sure what to do...

**Comment by owensto** [comment] 2015-11-29 18:33
Still not sure what to do, players can't sethome in the wilderness.

**Comment by drtshock** [comment] 2016-01-03 19:39
Duplicate of https://github.com/drtshock/Factions/issues/590

**Closed as completed by drtshock** 2016-01-03 19:39 UTC
