### ISSUE TITLE
F show lag

### ISSUE THREAD

**Issue by CullanP** [drtshock/Factions#195] opened 2014-12-29 20:35 UTC
I recently noticed that the lag with this plugin is unbearable and only because of cmdshow.java, I tested/debugged and this line "for (FPlayer p : MiscUtil.rankOrder(faction.getFPlayers())) {" is causing lag on my server. I compiled with craftbukkit 1.7.10 and am using spigot 1.7.10 latest. When not in a faction and doing /f show its the worst

**Comment by iaxedu** [comment] 2014-12-30 00:00
Basicly same issue as me: #193

**Comment by CullanP** [comment] 2014-12-30 00:19
He'll fix it :P : I gave him enough info to help find a solution.

**Comment by cnr** [comment] 2014-12-30 04:07
Duplicate of #193

**Closed as completed by cnr** 2014-12-30 04:07 UTC
