### ISSUE TITLE
Command freezing server

### ISSUE THREAD

**Issue by PhanaticD** [drtshock/Factions#587] opened 2015-12-13 03:15 UTC
http://pastebin.com/Q5Xzc0mT

**Comment by PhanaticD** [comment] 2015-12-27 21:23
anyone? http://pastebin.com/9NBi4pQc

**Comment by drtshock** [comment] 2015-12-28 19:54
Duplicate of https://github.com/drtshock/Factions/issues/579

**Closed as completed by drtshock** 2015-12-28 19:54 UTC
