### ISSUE TITLE
/f stuck or /f halp! teleports players outside of the faction

### ISSUE THREAD

**Issue by zacherygentry** [drtshock/Factions#1243] opened 2019-07-23 04:28 UTC
### FactionsUUID Version
v1.6.9.5-U0.4.3-b170

### Server Version
This server is running Paper version git-Paper-123 (MC: 1.14.3) (Implementing API version 1.14.3-R0.1-SNAPSHOT)

### Logs
Not needed

### Details
/f stuck teleports user outside of the faction. 
If the faction is on a worldborder, it also has the chance to teleport the player outside of the worldborder.

**Comment by uf0h** [comment] 2019-08-25 22:16
**Regarding this part of your details:**

> /f stuck teleports user outside of the faction.

This is not a bug but the established functionality; to search for a Wilderness claim within your radius and teleport you there.

**Comment by CmdrKittens** [comment] 2019-08-25 22:18
Resolved in above-linked PR #1284 to be in 0.5.0 release

**Closed as completed by CmdrKittens** 2019-08-25 22:18 UTC
Labels: bug needs confirmation
