### ISSUE TITLE
Sponge water/lava and Factionless sethome in Faction territory.

### ISSUE THREAD

**Issue by SnakeDaoust1232** [drtshock/Factions#602] opened 2015-12-30 06:05 UTC
Video Explanation: https://www.youtube.com/watch?v=JNJ8bl6jG0Q&feature=youtu.be

**Comment by drtshock** [comment] 2015-12-30 17:37
Can you explain in text please.

**Comment by juIio** [comment] 2015-12-30 19:33
The sponge issue has to do with another plugin, but we might be able to fix that by messing with priorities. As for the Factionless players, just add sethome to the denied list of commands in the config for "territoryEnemyDenyCommands"

**Comment by SnakeDaoust1232** [comment] 2015-12-30 22:19
See, i have the default relation set to enemy, and all the enemy deny commands set up, although faction-less players cant enemy wilderness. And if they could enemy wilderness, that would mean they wouldn't be able to set home anywhere but their claimed land, which is bad. Only if there was a way to make it so faction-less players couldn't set home in any faction territory, and it they did, because say, they joined the enemies faction and set home, then later planned on teleporting. If the plugin could deny teleporting into claims unless the claims are yours, wilderness, safezone, or warzone.

Factions Config: http://pastebin.com/K3vUdfFj

As for the sponge issue. Ill take a look at my plugins.

**Comment by SnakeDaoust1232** [comment] 2015-12-31 18:47
Update: I fixed the sponge issue although the faction-less player commands is still something that i personally would like to be added. If you guys dont want to add it, its ok, i understand.

**Comment by alexsatellite** [comment] 2016-01-03 19:52
how did you fix the sponge issue?

**Comment by drtshock** [comment] 2016-01-03 19:54
Duplicate of #590

**Closed as completed by drtshock** 2016-01-03 19:54 UTC
