### ISSUE TITLE
Annoying message

### ISSUE THREAD

**Issue by marium0505** [drtshock/Factions#520] opened 2015-08-31 22:19 UTC
Hello,

I have an annoying issue with the below messages keep spamming me whenever I move.
Based on what I have figured after some testing, are both of the messages sent when I am in a World Guard region with world guard support enabled, and only the first message when I move around in the wilderness chunks. 

![](http://i.imgur.com/C8QGVKj.png)

I would love to see this fixed, as it gets really spammy really fast...

Thanks in advance, and thanks for an awesome plugin, keep up the good work. :)

**Comment by drtshock** [comment] 2015-09-01 17:18
Can you paste your conf.json in a pastebin and give me your server log please. Also, can you give me a step by step on how to reproduce this and give me your FactionsUUID version ('latest' is not a version, I need the version string) as well as your Worldguard version.

**Comment by cnr** [comment] 2015-09-01 17:50
The first message should be fixed in the latest build on the CI.

The second message is there because you had `/f autoclaim` enabled.

**Closed as completed by cnr** 2015-09-01 17:50 UTC

**Comment by marium0505** [comment] 2015-09-01 19:07
Just want to confirm that the first message has indeed been removed/fixed in the latest build on the CI.
Thank you for the quick fix. :)

**Comment by cnr** [comment] 2015-09-01 22:32
It should be fixed, yes.
