### ISSUE TITLE
f vault

### ISSUE THREAD

**Issue by ZoneRaids** [drtshock/Factions#1172] opened 2018-08-16 20:59 UTC
16.08 16:53:50 [Server] INFO Mordicaai issued server command: /f vault 16.08 16:53:50 [Server] ERROR null 16.08 16:53:50 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'f' in plugin Factions v1.6.9.5-U0.2.2-b122 16.08 16:53:50 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paperspigot-1.8.8.jar:git-PaperSpigot-"4c7641d"] 16.08 16:53:50 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:146) ~[paperspigot-1.8.8.jar:git-PaperSpigot-"4c7641d"] 16.08 16:53:50 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:666) ~[paperspigot-1.8.8.jar:git-PaperSpigot-"4c7641d"] 16.08 16:53:50 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1189) [paperspigot-1.8.8.jar:git-PaperSpigot-"4c7641d"] 16.08 16:53:50 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1001) [paperspigot-1.8.8.jar:git-PaperSpigot-"4c7641d"] 16.08 16:53:50 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [paperspigot-1.8.8.jar:git-PaperSpigot-"4c7641d"] 16.08 16:53:50 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [paperspigot-1.8.8.jar:git-PaperSpigot-"4c7641d"] 16.08 16:53:50 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [paperspigot-1.8.8.jar:git-PaperSpigot-"4c7641d"] 16.08 16:53:50 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_171] 16.08 16:53:50 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_171] 16.08 16:53:50 [Server] INFO at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [paperspigot-1.8.8.jar:git-PaperSpigot-"4c7641d"] 16.08 16:53:50 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [paperspigot-1.8.8.jar:git-PaperSpigot-"4c7641d"] 16.08 16:53:50 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [paperspigot-1.8.8.jar:git-PaperSpigot-"4c7641d"] 16.08 16:53:50 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [paperspigot-1.8.8.jar:git-PaperSpigot-"4c7641d"] 16.08 16:53:50 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [paperspigot-1.8.8.jar:git-PaperSpigot-"4c7641d"] 16.08 16:53:50 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171] 16.08 16:53:50 [Server] INFO Caused by: java.lang.NoClassDefFoundError: com/drtshock/playervaults/translations/Lang 16.08 16:53:50 [Server] INFO at com.massivecraft.factions.cmd.CmdVault.perform(CmdVault.java:66) ~[?:?] 16.08 16:53:50 [Server] INFO at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:130) ~[?:?] 16.08 16:53:50 [Server] INFO at com.massivecraft.factions.cmd.FCommand.execute(FCommand.java:53) ~[?:?] 16.08 16:53:50 [Server] INFO at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:116) ~[?:?] 16.08 16:53:50 [Server] INFO at com.massivecraft.factions.cmd.FCommand.execute(FCommand.java:53) ~[?:?] 16.08 16:53:50 [Server] INFO at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:134) ~[?:?] 16.08 16:53:50 [Server] INFO at com.massivecraft.factions.zcore.MPlugin.handleCommand(MPlugin.java:295) ~[?:?] 16.08 16:53:50 [Server] INFO at com.massivecraft.factions.zcore.MPlugin.handleCommand(MPlugin.java:258) ~[?:?] 16.08 16:53:50 [Server] INFO at com.massivecraft.factions.P.handleCommand(P.java:251) ~[?:?] 16.08 16:53:50 [Server] INFO at com.massivecraft.factions.P.onCommand(P.java:262) ~[?:?] 16.08 16:53:50 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paperspigot-1.8.8.jar:git-PaperSpigot-"4c7641d"] 16.08 16:53:50 [Server] INFO ... 15 more

**Comment by Driftay** [comment] 2018-08-26 10:28
Install PlayerVaults

**Comment by ZoneRaids** [comment] 2018-08-26 21:15
i do have PlayerVaults installed

**Comment by drtshock** [comment] 2018-12-17 01:12
Duplicate of https://github.com/drtshock/Factions/issues/1168

**Closed as completed by drtshock** 2018-12-17 01:12 UTC
