### ISSUE TITLE
Disabling Enemys in /f show [HELP]

### ISSUE THREAD

**Issue by Lotteries** [drtshock/Factions#293] opened 2015-02-28 19:09 UTC
Not really a issue, but more of a question.
In the /f show it lists the 'Allys' and 'Enemies', is there  way to disable showing enemys in the /f show? Thanks :)

**Comment by drtshock** [comment] 2015-02-28 20:08
Currently no but we do aim to have /f show be 100% configurable which leads this to be a duplicate of https://github.com/drtshock/Factions/issues/166

**Closed as completed by drtshock** 2015-02-28 20:08 UTC
