### ISSUE TITLE
Factions Fly is canceled if a faction member hits another faction member in fly.

### ISSUE THREAD

**Issue by luwie556** [drtshock/Factions#1158] opened 2018-05-21 23:58 UTC
Version: b118

The bug is just as it states, in which when you are in the same faction and you hit another factions member that is in fly the flight of the faction member hit is turned off.

**Comment by dariasc** [comment] 2018-05-22 00:01
Just checked yes it get's disabled before it has a chance to check the damager and damagee, it is checked on a generic event before the Entity to Entity damage, I dont know what would be the best way to approach it

**Comment by VictorML11** [comment] 2018-07-05 18:33
Well yes in fact the problem is at **FactionsEntityListener** at 
public void onEntityDamage(EntityDamageEvent event)
First we check if the player can hurt the other player and we cancel the event but actually Factions does not cancel it as it is stated in a note.

So we actually always enter to this code:
`          if (damagee != null && damagee instanceof Player) {
                cancelFStuckTeleport((Player) damagee);
                cancelFFly((Player) damagee);
            }
            if (damager instanceof Player) {
                cancelFStuckTeleport((Player) damager);
                cancelFFly((Player) damager);
            }`

Which does not check if the damage was coming from same members.
I will make a fix for this and make a pull Request

**Comment by VictorML11** [comment] 2018-07-05 18:58
Error Solved @drtshock or someone should accept the Pull Request

**Comment by dariasc** [comment] 2018-07-21 16:37
Fixed in AutoFly PR at the private repo by adding a return after cancelling the event leading to no duplicate code

**Closed as completed** 2019-07-09 06:25 UTC
