### ISSUE TITLE
Neutral deny commands not working properly?

### ISSUE THREAD

**Issue by alexsatellite** [drtshock/Factions#605] opened 2016-01-01 15:55 UTC
Hey I'm trying to deny /sethome and /esethome in neutral claims but it should not affect wilderness territory right? because you have a specific option for wilderness:  "wildernessDenyCommands": [],
so If I deny the commands here: "territoryNeutralDenyCommands": []  They cant use /sethome in wilderness so plz what can I do? is a plugin problem or I need to do other thing for fix this.
If it's a problem of your plugin can you fix this fast plz this is so annoying.

**Comment by Educationals** [comment] 2016-01-01 19:03
I have the same problem, please solve.

**Comment by alexsatellite** [comment] 2016-01-03 13:35
This bug is important and it should be already fixed. C'mon.....  itzmonkey already found the problem.

**Comment by Educationals** [comment] 2016-01-03 14:27
How fix??

**Comment by alexsatellite** [comment] 2016-01-03 15:13
You can install the version of august, but I cant because I'm using addons which needs the latest version to work.

**Comment by drtshock** [comment] 2016-01-03 19:39
Duplicate of https://github.com/drtshock/Factions/issues/590

**Closed as completed by drtshock** 2016-01-03 19:39 UTC
