### ISSUE TITLE
[Request]

### ISSUE THREAD

**Issue by FutureDev1** [drtshock/Factions#439] opened 2015-06-19 15:04 UTC
I would really appreciate being able to customize /f map to a greater extent. I would like to be able to make the symbol that shows when there is no land there, default &7- to a &f&l(Square Symbol) then show a colored square for land where people claim land. For the land claim symbols, I would like to alter the order of which they appear, depending on how many claims are in the radius, it will cycle through the amount of distinct symbols, but I would like them to just be altered colors. Thanks for reading this and I hope it gets added. It would definitely be a unique edition compared to MassiveCore Factions.

**Comment by drtshock** [comment] 2015-09-08 17:42
Duplicate of #482

**Closed as completed by drtshock** 2015-09-08 17:42 UTC
