### ISSUE TITLE
Scoreboard Bugs

### ISSUE THREAD

**Issue by ColtraneNadler** [drtshock/Factions#47] opened 2014-08-31 22:16 UTC
issue w/ sb

**Comment by drtshock** [comment] 2014-08-31 22:17
I'm not going to show scoreboard AND chat. I'll look into the other parts of your issue.

**Comment by drtshock** [comment] 2014-09-05 13:58
Wasn't able to reproduce. Can anyone else reproduce this?

**Comment by RenegadeEagle** [comment] 2014-10-05 20:49
Closing this now due to the reporter of this topic is no longer active in any aspect of minecraft.

**Closed as completed by RenegadeEagle** 2014-10-05 20:49 UTC
