### ISSUE TITLE
console spam

### ISSUE THREAD

**Issue by random1167** [drtshock/Factions#719] opened 2016-06-04 08:42 UTC
`[Factions v1.6.9.5-U0.1.19-RC1] PLAYER was going to be auto-removed but was set not to.`
i get spammed by this message every few mins, can someone please tell this fool ""me"" whats what,thank you

**Comment by tristiisch** [comment] 2016-06-04 18:39
I have the same bug

**Comment by Kakifrucht** [comment] 2016-06-04 18:41
Duplicate of #706

**Comment by drtshock** [comment] 2016-06-05 18:22
Not an issue. It's just a leftover debug message that has since been removed.

**Closed as completed by drtshock** 2016-06-05 18:22 UTC

**Comment by random1167** [comment] 2016-06-05 22:05
so to get this update i need to build my own factions jar? i dont see an update on spigot

**Comment by drtshock** [comment] 2016-06-06 17:52
Yeah it's not on spigot yet.
