### ISSUE TITLE
Feature Request?

### ISSUE THREAD

**Issue by KriticalPvP** [drtshock/Factions#345] opened 2015-04-02 21:45 UTC
Would it be possible to add::

1) color of name tags ( depending on relation )

2) /f motd ( shows faction members what the leader has /f motd'd )

3) tells you who killed your faction member and what faction they were/are in!

4) when someone from your fac leaves / joins

5) add a friendly fire command? /f friendlyfire 

Thanks!

**Comment by drtshock** [comment] 2015-04-03 17:17
1) already done
2) we have /f announce
3) yes make a ticket for that
4) /f login
5) you'd have to explain this in more detail

**Comment by KriticalPvP** [comment] 2015-04-03 19:29
1) How can I set all factions to automatically have /f login? and they can't disable it?

2) could you make it so when a user hits negative power. eg they die, loose 4 power and their power is now -2 output a command? I'm using ban manager so I'd like a negative power deathban...
3) /f friendlyfire allows you to hit faction members as long as they both have /f friendlyfire on...

**Comment by drtshock** [comment] 2015-09-08 18:04
1 is a duplicate of #367. 
2 write a plugin that listens to power change event.
3 what? we don't have that option.

**Closed as completed by drtshock** 2015-09-08 18:04 UTC
