### ISSUE TITLE
Exception when doing /f show on a faction with a desc containing %s

### ISSUE THREAD

**Issue by Tibowl** [drtshock/Factions#483] opened 2015-07-28 21:28 UTC
Exception: http://pastebin.com/Vtt1rBpn

Reproduce: Do /f desc %s
Then do /f who: 

![Example](http://i.imgur.com/ohyOzo7.png)

**Comment by drtshock** [comment] 2015-08-06 21:10
Duplicate of #490 and fixed.

**Closed as completed by drtshock** 2015-08-06 21:10 UTC
