### ISSUE TITLE
/f vault

### ISSUE THREAD

**Issue by Avizoh** [drtshock/Factions#1173] opened 2018-08-27 02:21 UTC
FactionsUUID version (run `/f version`): FactionsUUID 1.6.9.5-U0.2.2-b116

Server software (run `/version`): 1.8.8 TacoSpigot (Custom)

Server (`logs/latest.log`): https://hastebin.com/efelajehad.apache

Details:

**Comment by drtshock** [comment] 2018-12-17 01:12
Duplicate of https://github.com/drtshock/Factions/issues/1168

**Closed as completed by drtshock** 2018-12-17 01:12 UTC
