### ISSUE TITLE
/f warps Again!!

### ISSUE THREAD

**Issue by alexsatellite** [drtshock/Factions#517] opened 2015-08-31 00:34 UTC
Important, please fix, if you type /f warps "warp-name" you dont have cool down but if you type / f warp "warp-name" it works fine. Please remove all of these commands that bypass the cool down because is stupid.

**Comment by drtshock** [comment] 2015-08-31 15:46
Duplicate of #504

**Closed as completed by drtshock** 2015-08-31 15:46 UTC
