### ISSUE TITLE
/f chat doesn't respect chat plugins

### ISSUE THREAD

**Issue by TheKnight787** [drtshock/Factions#37] opened 2014-07-23 17:39 UTC
I have a plugin that doesn't allow you to advertise domains and ips. But whenever I type an ip while beeing in ally or faction chat it doesn't block it. The plugin gives the warning to the player to not advertise but doesn't block it from appearing in the chat.

**Comment by drtshock** [comment] 2014-08-02 21:57
Factions has never done this :\

**Comment by TheKnight787** [comment] 2014-08-06 11:25
I mean the plugins, that should block some kind of words or numbers don't work, when /f chat is in ally or faction mode.

**Comment by drtshock** [comment] 2014-08-06 18:13
I know, factions has never worked like this though. So this is a legacy bug / enhancement.

**Comment by squidicuzz** [comment] 2014-10-25 01:18
This could be fixed if the chat handling was reworked.  It would take a bit of work.  I will look into it this more in the future if there is a want for it.

**Comment by drtshock** [comment] 2014-11-20 15:19
Duplicate of #100

**Closed as completed by drtshock** 2014-11-20 15:19 UTC
Labels: bug, enhancement
