### ISSUE TITLE
Pex Prefix/Suffix ?

### ISSUE THREAD

**Issue by Miaourt** [drtshock/Factions#31] opened 2014-07-12 20:26 UTC
Hey ! This would be a nice thing is we can see, in the near future, pex suffix and prefix support, directly in the "chat tag" of faction uuid :)

**Comment by drtshock** [comment] 2014-07-12 20:32
What do you mean specifically?

**Comment by Miaourt** [comment] 2014-07-12 20:36
We have that : 
[...]
  "chatTagEnabled": false,
  "chatTagRelationColored": true,
  "chatTagReplaceString": "[FACTION]",
  "chatTagInsertAfterString": "",
  "chatTagInsertBeforeString": "",
  "chatTagInsertIndex": 1,
  "chatTagPadBefore": false,
  "chatTagPadAfter": true,
  "chatTagFormat": "%s§f",
  "factionChatFormat": "%s:§f %s",
  "allianceChatFormat": "§d%s:§f %s",
[...]
so, i want to know (if this is not implemented, i'm sorry for ask if that ^^') if whe can.... "insert" somewhere PermissionEx's suffix and prefix (thank for reading, and sorry for my crappy english ><)

**Comment by TheKnight787** [comment] 2014-07-13 18:11
Change

"chatTagInsertIndex": 1,

To

"chatTagInsertIndex": 3,

**Comment by Miaourt** [comment] 2014-07-13 18:24
Ah, thank, and i put... ewh.... what for say to pex where to put the prefix/suffix ? ^^'

**Comment by Miaourt** [comment] 2014-07-14 21:16
So, i think permissionEx donsn't send "tag" like %suffix or [suffix] so it seem to be something the chat managing plugin (here faction .-. ) should hook... if this is possible...?

**Comment by TheKnight787** [comment] 2014-07-16 11:42
I am using EssentialsChat and it's working fine for me.

**Comment by Miaourt** [comment] 2014-07-16 21:18
That is the problem, i don't use essential, and i don't want to use a chat manager plugin :o i use PermissionEx for permission management (and prefix/suffix) sor i wanted to know if faction could add support for a Pex tag in the "chat management", like the %s :')

**Comment by drtshock** [comment] 2014-11-20 15:19
Duplicate of #100

**Closed as completed by drtshock** 2014-11-20 15:19 UTC
Labels: enhancement
