### ISSUE TITLE
Players can place water in WarZone

### ISSUE THREAD

**Issue by EliteWhopper** [drtshock/Factions#251] opened 2015-02-09 00:24 UTC
I noticed that players can't break any block in WarZone etc, but they can place items hence, water, lava, spawn eggs, etc. I hope you can fix this because it gets annoying having to put out the water and lava, hah. Have a good one and thank you.

**Comment by cnr** [comment] 2015-02-09 00:56
Is `warZoneDenyBuild` set to `true` in conf.json? If so, I can't reproduce -- please paste your conf.json in a [gist](https://gist.github.com)

**Comment by EliteWhopper** [comment] 2015-02-09 09:35
Yes, it is.
https://gist.github.com/EliteWhopper/36c4f5e887d26122023b

**Comment by cnr** [comment] 2015-02-11 20:18
Does this happen when Factions is the only installed plugin on the server?

**Comment by EliteWhopper** [comment] 2015-02-16 23:23
Yes.

**Comment by aeonlamb** [comment] 2019-04-05 18:14
This is still happening. Players can place buckets of lava and buckets of water inside of safezone & warzone. Happens on 1.6.9.5-U0.3.0-b133, Paper 1.13.2 .

**Comment by CmdrKittens** [comment] 2020-08-10 19:40
Resolved in upcoming release. This was a quirk of several settings overlapping that are not defaults, so it was hard to catch until now.

**Closed as completed by CmdrKittens** 2020-08-10 19:40 UTC
Labels: bug confirmed
