### ISSUE TITLE
/f who error

### ISSUE THREAD

**Issue by LemonNick** [drtshock/Factions#489] opened 2015-08-01 08:49 UTC
[19:48:46] [Server thread/INFO]: test issued server command: /f who
[19:48:46] [Server thread/WARN]: java.lang.ClassNotFoundException: net/minecraft/server/v1_7_R4/PacketPlayOutChat
[19:48:46] [Server thread/WARN]: at java.lang.Class.forName0(Native Method)
[19:48:46] [Server thread/WARN]: at java.lang.Class.forName(Class.java:195)
[19:48:46] [Server thread/WARN]: at net.amoebaman.util.Reflection.getNMSClass(Reflection.java:64)
[19:48:46] [Server thread/WARN]: at com.massivecraft.factions.shade.mkremins.fanciful.FancyMessage.<init>(FancyMessage.java:89)
[19:48:46] [Server thread/WARN]: at com.massivecraft.factions.shade.mkremins.fanciful.FancyMessage.<init>(FancyMessage.java:78)
[19:48:46] [Server thread/WARN]: at com.massivecraft.factions.zcore.util.TextUtil.toFancy(TextUtil.java:67)
[19:48:46] [Server thread/WARN]: at com.massivecraft.factions.zcore.util.TextUtil.parseFancy(TextUtil.java:62)
[19:48:46] [Server thread/WARN]: at com.massivecraft.factions.zcore.util.TagUtil.getFancy(TagUtil.java:125)
[19:48:46] [Server thread/WARN]: at com.massivecraft.factions.zcore.util.TagUtil.parseFancy(TagUtil.java:90)
[19:48:46] [Server thread/WARN]: at com.massivecraft.factions.cmd.CmdShow.perform(CmdShow.java:82)
[19:48:46] [Server thread/WARN]: at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:130)
[19:48:46] [Server thread/WARN]: at com.massivecraft.factions.cmd.FCommand.execute(FCommand.java:53)
[19:48:46] [Server thread/WARN]: at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:116)
[19:48:46] [Server thread/WARN]: at com.massivecraft.factions.cmd.FCommand.execute(FCommand.java:53)
[19:48:46] [Server thread/WARN]: at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:134)
[19:48:46] [Server thread/WARN]: at com.massivecraft.factions.zcore.MPlugin.handleCommand(MPlugin.java:302)
[19:48:46] [Server thread/WARN]: at com.massivecraft.factions.zcore.MPlugin.handleCommand(MPlugin.java:265)
[19:48:46] [Server thread/WARN]: at com.massivecraft.factions.P.handleCommand(P.java:180)
[19:48:46] [Server thread/WARN]: at com.massivecraft.factions.P.onCommand(P.java:192)
[19:48:46] [Server thread/WARN]: at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[19:48:46] [Server thread/WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181)
[19:48:46] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:717)
[19:48:46] [Server thread/WARN]: at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1317)
[19:48:46] [Server thread/WARN]: at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1099)
[19:48:46] [Server thread/WARN]: at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:38)
[19:48:46] [Server thread/WARN]: at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:53)
[19:48:46] [Server thread/WARN]: at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244)
[19:48:46] [Server thread/WARN]: at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173)
[19:48:46] [Server thread/WARN]: at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:991)
[19:48:46] [Server thread/WARN]: at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
[19:48:46] [Server thread/WARN]: at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809)
[19:48:46] [Server thread/WARN]: at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669)
[19:48:46] [Server thread/WARN]: at java.lang.Thread.run(Thread.java:745)
[19:48:46] [Server thread/WARN]: java.lang.ClassNotFoundException: net/minecraft/server/v1_7_R4/IChatBaseComponent
[19:48:46] [Server thread/WARN]: at java.lang.Class.forName0(Native Method)
[19:48:46] [Server thread/WARN]: at java.lang.Class.forName(Class.java:195)
[19:48:46] [Server thread/WARN]: at net.amoebaman.util.Reflection.getNMSClass(Reflection.java:64)
[19:48:46] [Server thread/WARN]: at com.massivecraft.factions.shade.mkremins.fanciful.FancyMessage.<init>(FancyMessage.java:89)
[19:48:46] [Server thread/WARN]: at com.massivecraft.factions.shade.mkremins.fanciful.FancyMessage.<init>(FancyMessage.java:78)
[19:48:46] [Server thread/WARN]: at com.massivecraft.factions.zcore.util.TextUtil.toFancy(TextUtil.java:67)
[19:48:46] [Server thread/WARN]: at com.massivecraft.factions.zcore.util.TextUtil.parseFancy(TextUtil.java:62)
[19:48:46] [Server thread/WARN]: at com.massivecraft.factions.zcore.util.TagUtil.getFancy(TagUtil.java:125)
[19:48:46] [Server thread/WARN]: at com.massivecraft.factions.zcore.util.TagUtil.parseFancy(TagUtil.java:90)
[19:48:46] [Server thread/WARN]: at com.massivecraft.factions.cmd.CmdShow.perform(CmdShow.java:82)
[19:48:46] [Server thread/WARN]: at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:130)
[19:48:46] [Server thread/WARN]: at com.massivecraft.factions.cmd.FCommand.execute(FCommand.java:53)
[19:48:46] [Server thread/WARN]: at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:116)
[19:48:46] [Server thread/WARN]: at com.massivecraft.factions.cmd.FCommand.execute(FCommand.java:53)
[19:48:46] [Server thread/WARN]: at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:134)
[19:48:46] [Server thread/WARN]: at com.massivecraft.factions.zcore.MPlugin.handleCommand(MPlugin.java:302)
[19:48:46] [Server thread/WARN]: at com.massivecraft.factions.zcore.MPlugin.handleCommand(MPlugin.java:265)
[19:48:46] [Server thread/WARN]: at com.massivecraft.factions.P.handleCommand(P.java:180)
[19:48:46] [Server thread/WARN]: at com.massivecraft.factions.P.onCommand(P.java:192)
[19:48:46] [Server thread/WARN]: at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[19:48:46] [Server thread/WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181)
[19:48:46] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:717)
[19:48:46] [Server thread/WARN]: at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1317)
[19:48:46] [Server thread/WARN]: at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1099)
[19:48:46] [Server thread/WARN]: at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:38)
[19:48:46] [Server thread/WARN]: at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:53)
[19:48:46] [Server thread/WARN]: at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244)
[19:48:46] [Server thread/WARN]: at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173)
[19:48:46] [Server thread/WARN]: at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:991)
[19:48:46] [Server thread/WARN]: at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
[19:48:46] [Server thread/WARN]: at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809)
[19:48:46] [Server thread/WARN]: at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669)
[19:48:46] [Server thread/WARN]: at java.lang.Thread.run(Thread.java:745)
[19:48:46] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'f' in plugin Factions v1.6.9.5-U0.1.17-b270
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[PluginCommand.class:1.7.10-1481.146]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) ~[SimpleCommandMap.class:1.7.10-1481.146]
at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:717) ~[CraftServer.class:1.7.10-1481.146]
at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1317) [nh.class:?]
at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1099) [nh.class:?]
at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:38) [ir.class:?]
at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:53) [ir.class:?]
at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244) [ej.class:?]
at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:991) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:745) [?:1.7.0_80]
Caused by: java.lang.NullPointerException
at com.massivecraft.factions.shade.mkremins.fanciful.FancyMessage.<init>(FancyMessage.java:89) ~[?:?]
at com.massivecraft.factions.shade.mkremins.fanciful.FancyMessage.<init>(FancyMessage.java:78) ~[?:?]
at com.massivecraft.factions.zcore.util.TextUtil.toFancy(TextUtil.java:67) ~[?:?]
at com.massivecraft.factions.zcore.util.TextUtil.parseFancy(TextUtil.java:62) ~[?:?]
at com.massivecraft.factions.zcore.util.TagUtil.getFancy(TagUtil.java:125) ~[?:?]
at com.massivecraft.factions.zcore.util.TagUtil.parseFancy(TagUtil.java:90) ~[?:?]
at com.massivecraft.factions.cmd.CmdShow.perform(CmdShow.java:82) ~[?:?]
at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:130) ~[?:?]
at com.massivecraft.factions.cmd.FCommand.execute(FCommand.java:53) ~[?:?]
at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:116) ~[?:?]
at com.massivecraft.factions.cmd.FCommand.execute(FCommand.java:53) ~[?:?]
at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:134) ~[?:?]
at com.massivecraft.factions.zcore.MPlugin.handleCommand(MPlugin.java:302) ~[?:?]
at com.massivecraft.factions.zcore.MPlugin.handleCommand(MPlugin.java:265) ~[?:?]
at com.massivecraft.factions.P.handleCommand(P.java:180) ~[?:?]
at com.massivecraft.factions.P.onCommand(P.java:192) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[PluginCommand.class:1.7.10-1481.146]
... 13 more

Server version 1.7.10

**Comment by Agazed** [comment] 2015-08-01 12:11
Update to 1.8.8

**Comment by LemonNick** [comment] 2015-08-01 15:53
A fix is not?

**Comment by LemonNick** [comment] 2015-08-01 15:54
And to correct the error? Some use on version 1.7.10. The author claims that this version should work.I am waiting for a fix.

**Comment by drtshock** [comment] 2015-08-01 18:06
Can you use pastebin pls

**Comment by drtshock** [comment] 2015-08-06 22:03
Duplicate of https://github.com/drtshock/Factions/issues/487 (same issue, different command).

**Closed as completed by drtshock** 2015-08-06 22:03 UTC
