### ISSUE TITLE
Issue with "territoryNeutralDenyCommands" and "wildernessDenyCommands"

### ISSUE THREAD

**Issue by Radero** [drtshock/Factions#540] opened 2015-10-03 14:05 UTC
I add deny commands when my players can set a home in territory neutral and when they want sethome in wilderness they received : "You can't use the command /sethome in neutral territory.
Wilderness is defined by neutral but my players can't sethome in worlds ...

**Comment by juIio** [comment] 2015-10-04 08:00
I tried replicating the issue but couldn't do it.

http://prntscr.com/8nj9mr
http://prntscr.com/8nj9nw

I have the sethome command denied in neutral territory. http://prntscr.com/8nj9wp

As seen on the screenshots above, I can't set my home in Neutral territory but I can do it in Wilderness. Can you show us your Conf.json file?

**Comment by Radero** [comment] 2015-10-04 16:53
When player is in faction he can't sethome in wilderness because wilderness is a neutral territory for a faction i think.

**Comment by juIio** [comment] 2015-10-04 19:12
@Radero please post your Conf.json file on http://pastebin.com and show it to us here.

**Comment by fhebuterne** [comment] 2015-10-10 21:57
"territoryNeutralDenyCommands": [  
    "home",
    "sethome",
    "spawn",
    "tpahere",
    "tpaccept",
    "tpa"
  ],
  "territoryEnemyDenyCommands": [
    "home",
    "sethome",
    "spawn",
    "tpahere",
    "tpaccept",
    "tpa"
  ],
  "territoryAllyDenyCommands": [],
  "warzoneDenyCommands": [],
  "wildernessDenyCommands": [],

You can download my test configuration (it's not my real config but the bug is present) : http://pastebin.com/54GYTuMW

I've confirmed this bug because when i'm in wilderness i can't send /sethome.
I've an error : "You can't use the command '/sethome' in neutral territory"

But i'm in wilderness, it's very problematic for my players. Please could you fix this ?

Sincerely,
Fabien

![bug](https://cloud.githubusercontent.com/assets/5675697/10413494/416bffe2-6fab-11e5-878b-8bcb17c30069.jpg)

**Comment by juIio** [comment] 2015-10-10 22:18
What version of factions are you running?

**Comment by fhebuterne** [comment] 2015-10-10 22:20
version: 1.6.9.5-U0.1.18-b298

**Comment by fhebuterne** [comment] 2015-10-20 12:16
Up ?

**Comment by CmdrKittens** [comment] 2019-07-10 02:45
I am closing this issue due to its age with the assumption it is no longer a problem. If you encounter this problem, or a similar problem, please create a new issue for it.

**Closed as completed by CmdrKittens** 2019-07-10 02:45 UTC
