### ISSUE TITLE
Mutes are bypassed with factions using BanManager's Mute functions.

### ISSUE THREAD

**Issue by Leopere** [drtshock/Factions#110] opened 2014-11-06 22:55 UTC
https://imgur.com/jYTwGkv

**Comment by Leopere** [comment] 2014-11-06 22:58
Ticket as reported by one of my mods:

Muted people are able to use faction ally chat.

Not sure if its a big issue, however muted people still have access to /f chat ally & can continue to speak through those means. It does tell them that they are muted and such, but the messages still go through.
I used my alts to test this, and can provide proof here:
http://puu.sh/bqXx6/28093636ee.png http://puu.sh/bqXyg/b457a3f59b.png

**Comment by drtshock** [comment] 2014-11-06 22:59
Yes I'm aware of this. It's how this plugin handles chat. It cancels the event in the case of ally / faction chat instead of modifying the recipients list. The entire chat system really needs a complete rewrite.

**Comment by squidicuzz** [comment] 2014-11-09 01:22
That is why it did get a rewrite in future versions...

**Comment by drtshock** [comment] 2014-11-20 15:19
Duplicate of #100

**Closed as completed by drtshock** 2014-11-20 15:19 UTC
Labels: bug
