### ISSUE TITLE
I have a problem with the scoreboard plugin factions uuid

### ISSUE THREAD

**Issue by dylan97** [drtshock/Factions#182] opened 2014-12-14 03:45 UTC
I have a problem with the scoreboard no error in console config setup well but the scoreboard does not appear when you log in or create a faction perpiacere can you help me

**Comment by Kakifrucht** [comment] 2014-12-14 22:01
This is probably a duplicate of this issue: https://github.com/drtshock/Factions/issues/93

**Comment by drtshock** [comment] 2014-12-14 22:58
^ what kaki said.

**Closed as completed by drtshock** 2014-12-14 22:58 UTC
