### ISSUE TITLE
Colors with Scoreboards Issue

### ISSUE THREAD

**Issue by jonahJS** [drtshock/Factions#1299] opened 2019-09-17 05:20 UTC
### FactionsUUID Version
*Run `/f version` and give us your output.* 
![Screenshot 2019-09-17 01 17 22](https://user-images.githubusercontent.com/20120646/65013387-ef480e80-d8e8-11e9-88be-32d617c2eccf.png)

### Server Version
*Run `/version` and give us your output.*
![Screenshot 2019-09-17 01 17 31](https://user-images.githubusercontent.com/20120646/65013391-f111d200-d8e8-11e9-8969-7883dc4d77c7.png)

### Logs
*Give use your logs by going to `logs/latest.log`.*
https://gist.github.com/jonahJS/6aaf714c4119692472038e9fae9d1367

### Details
Issue with scoreboard - I believe it's caused by not having enough character limit in each line? 

Here are examples: 
### 1
![Screenshot 2019-09-17 00 53 40](https://user-images.githubusercontent.com/20120646/65013452-23bbca80-d8e9-11e9-9bad-9771a56664e7.png)
![Screenshot 2019-09-17 00 53 29](https://user-images.githubusercontent.com/20120646/65013453-23bbca80-d8e9-11e9-945c-4f6ffad77ce4.png)

### 2
![Screenshot 2019-09-17 01 17 12](https://user-images.githubusercontent.com/20120646/65013458-2a4a4200-d8e9-11e9-881c-9216622cbbae.png)
![Screenshot 2019-09-17 01 17 07](https://user-images.githubusercontent.com/20120646/65013459-2a4a4200-d8e9-11e9-80e6-b5b02730e388.png)

**Comment by CmdrKittens** [comment] 2019-09-29 01:43
Duplicate of #1292 

Would love to fix this soon.

**Closed as completed by CmdrKittens** 2019-09-29 01:43 UTC
Labels: duplicate
