### ISSUE TITLE
f who error

### ISSUE THREAD

**Issue by bobzilla123** [drtshock/Factions#527] opened 2015-09-09 12:30 UTC
Im using your plugin and everytime i use /f who or faction who i get an internal command error
Im using the lastest version and my server is on 1.7.10
Should i use a different version for 1.7.10, if so, which version do you recommend

[08:20:18] [Server thread/WARN]: java.lang.ClassNotFoundException: net/minecraft/server/v1_7_R4/PacketPlayOutChat
[08:20:18] [Server thread/WARN]: at java.lang.Class.forName0(Native Method)
[08:20:18] [Server thread/WARN]: at java.lang.Class.forName(Class.java:264)
[08:20:18] [Server thread/WARN]: at net.amoebaman.util.Reflection.getNMSClass(Reflection.java:64)
[08:20:18] [Server thread/WARN]: at com.massivecraft.factions.shade.mkremins.fanciful.FancyMessage.<init>(FancyMessage.java:89)
[08:20:18] [Server thread/WARN]: at com.massivecraft.factions.shade.mkremins.fanciful.FancyMessage.<init>(FancyMessage.java:78)
[08:20:18] [Server thread/WARN]: at com.massivecraft.factions.zcore.util.TextUtil.toFancy(TextUtil.java:67)
[08:20:18] [Server thread/WARN]: at com.massivecraft.factions.zcore.util.TextUtil.parseFancy(TextUtil.java:62)
[08:20:18] [Server thread/WARN]: at com.massivecraft.factions.zcore.util.TagUtil.getFancy(TagUtil.java:132)
[08:20:18] [Server thread/WARN]: at com.massivecraft.factions.zcore.util.TagUtil.parseFancy(TagUtil.java:95)
[08:20:18] [Server thread/WARN]: at com.massivecraft.factions.cmd.CmdShow.perform(CmdShow.java:85)
[08:20:18] [Server thread/WARN]: at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:130)
[08:20:18] [Server thread/WARN]: at com.massivecraft.factions.cmd.FCommand.execute(FCommand.java:53)
[08:20:18] [Server thread/WARN]: at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:116)
[08:20:18] [Server thread/WARN]: at com.massivecraft.factions.cmd.FCommand.execute(FCommand.java:53)
[08:20:18] [Server thread/WARN]: at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:134)
[08:20:18] [Server thread/WARN]: at com.massivecraft.factions.zcore.MPlugin.handleCommand(MPlugin.java:302)
[08:20:18] [Server thread/WARN]: at com.massivecraft.factions.zcore.MPlugin.handleCommand(MPlugin.java:265)
[08:20:18] [Server thread/WARN]: at com.massivecraft.factions.P.handleCommand(P.java:180)
[08:20:18] [Server thread/WARN]: at com.massivecraft.factions.P.onCommand(P.java:192)
[08:20:18] [Server thread/WARN]: at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[08:20:18] [Server thread/WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181)
[08:20:18] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:717)
[08:20:18] [Server thread/WARN]: at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1317)
[08:20:18] [Server thread/WARN]: at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1099)
[08:20:18] [Server thread/WARN]: at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:38)
[08:20:18] [Server thread/WARN]: at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:53)
[08:20:18] [Server thread/WARN]: at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244)
[08:20:18] [Server thread/WARN]: at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173)
[08:20:18] [Server thread/WARN]: at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:991)
[08:20:18] [Server thread/WARN]: at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
[08:20:18] [Server thread/WARN]: at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809)
[08:20:18] [Server thread/WARN]: at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669)
[08:20:18] [Server thread/WARN]: at java.lang.Thread.run(Thread.java:745)
[08:20:18] [Server thread/WARN]: java.lang.ClassNotFoundException: net/minecraft/server/v1_7_R4/IChatBaseComponent
[08:20:18] [Server thread/WARN]: at java.lang.Class.forName0(Native Method)
[08:20:18] [Server thread/WARN]: at java.lang.Class.forName(Class.java:264)
[08:20:18] [Server thread/WARN]: at net.amoebaman.util.Reflection.getNMSClass(Reflection.java:64)
[08:20:18] [Server thread/WARN]: at com.massivecraft.factions.shade.mkremins.fanciful.FancyMessage.<init>(FancyMessage.java:89)
[08:20:18] [Server thread/WARN]: at com.massivecraft.factions.shade.mkremins.fanciful.FancyMessage.<init>(FancyMessage.java:78)
[08:20:18] [Server thread/WARN]: at com.massivecraft.factions.zcore.util.TextUtil.toFancy(TextUtil.java:67)
[08:20:18] [Server thread/WARN]: at com.massivecraft.factions.zcore.util.TextUtil.parseFancy(TextUtil.java:62)
[08:20:18] [Server thread/WARN]: at com.massivecraft.factions.zcore.util.TagUtil.getFancy(TagUtil.java:132)
[08:20:18] [Server thread/WARN]: at com.massivecraft.factions.zcore.util.TagUtil.parseFancy(TagUtil.java:95)
[08:20:18] [Server thread/WARN]: at com.massivecraft.factions.cmd.CmdShow.perform(CmdShow.java:85)
[08:20:18] [Server thread/WARN]: at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:130)
[08:20:18] [Server thread/WARN]: at com.massivecraft.factions.cmd.FCommand.execute(FCommand.java:53)
[08:20:18] [Server thread/WARN]: at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:116)
[08:20:18] [Server thread/WARN]: at com.massivecraft.factions.cmd.FCommand.execute(FCommand.java:53)
[08:20:18] [Server thread/WARN]: at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:134)
[08:20:18] [Server thread/WARN]: at com.massivecraft.factions.zcore.MPlugin.handleCommand(MPlugin.java:302)
[08:20:18] [Server thread/WARN]: at com.massivecraft.factions.zcore.MPlugin.handleCommand(MPlugin.java:265)
[08:20:18] [Server thread/WARN]: at com.massivecraft.factions.P.handleCommand(P.java:180)
[08:20:18] [Server thread/WARN]: at com.massivecraft.factions.P.onCommand(P.java:192)
[08:20:18] [Server thread/WARN]: at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[08:20:18] [Server thread/WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181)
[08:20:18] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:717)
[08:20:18] [Server thread/WARN]: at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1317)
[08:20:18] [Server thread/WARN]: at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1099)
[08:20:18] [Server thread/WARN]: at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:38)
[08:20:18] [Server thread/WARN]: at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:53)
[08:20:18] [Server thread/WARN]: at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244)
[08:20:18] [Server thread/WARN]: at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173)
[08:20:18] [Server thread/WARN]: at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:991)
[08:20:18] [Server thread/WARN]: at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
[08:20:18] [Server thread/WARN]: at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809)
[08:20:18] [Server thread/WARN]: at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669)
[08:20:18] [Server thread/WARN]: at java.lang.Thread.run(Thread.java:745)
[08:20:18] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'f' in plugin Factions v1.6.9.5-U0.1.18-b284
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[PluginCommand.class:1.7.10-1492.150]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) ~[SimpleCommandMap.class:1.7.10-1492.150]
at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:717) ~[CraftServer.class:1.7.10-1492.150]
at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1317) [nh.class:?]
at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1099) [nh.class:?]
at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:38) [ir.class:?]
at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:53) [ir.class:?]
at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244) [ej.class:?]
at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:991) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
Caused by: java.lang.NullPointerException
at com.massivecraft.factions.shade.mkremins.fanciful.FancyMessage.<init>(FancyMessage.java:89) ~[?:?]
at com.massivecraft.factions.shade.mkremins.fanciful.FancyMessage.<init>(FancyMessage.java:78) ~[?:?]
at com.massivecraft.factions.zcore.util.TextUtil.toFancy(TextUtil.java:67) ~[?:?]
at com.massivecraft.factions.zcore.util.TextUtil.parseFancy(TextUtil.java:62) ~[?:?]
at com.massivecraft.factions.zcore.util.TagUtil.getFancy(TagUtil.java:132) ~[?:?]
at com.massivecraft.factions.zcore.util.TagUtil.parseFancy(TagUtil.java:95) ~[?:?]
at com.massivecraft.factions.cmd.CmdShow.perform(CmdShow.java:85) ~[?:?]
at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:130) ~[?:?]
at com.massivecraft.factions.cmd.FCommand.execute(FCommand.java:53) ~[?:?]
at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:116) ~[?:?]
at com.massivecraft.factions.cmd.FCommand.execute(FCommand.java:53) ~[?:?]
at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:134) ~[?:?]
at com.massivecraft.factions.zcore.MPlugin.handleCommand(MPlugin.java:302) ~[?:?]
at com.massivecraft.factions.zcore.MPlugin.handleCommand(MPlugin.java:265) ~[?:?]
at com.massivecraft.factions.P.handleCommand(P.java:180) ~[?:?]
at com.massivecraft.factions.P.onCommand(P.java:192) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[PluginCommand.class:1.7.10-1492.150]

**Comment by drtshock** [comment] 2015-09-09 16:41
Duplicate of https://github.com/drtshock/Factions/issues/487

**Closed as completed by drtshock** 2015-09-09 16:41 UTC

**Comment by bobzilla123** [comment] 2015-09-09 20:56
redownloading the jar didnt help.
Im using cauldron if that means anything

**Comment by drtshock** [comment] 2015-09-10 16:31
oh, that makes more sense then. but cauldron isn't being supported anymore.
