### ISSUE TITLE
/f unclaim

### ISSUE THREAD

**Issue by Leopere** [drtshock/Factions#123] opened 2014-11-10 05:08 UTC
Factions version info via Plugman: 

```
[23:52:58 INFO]: [PlugMan] Plugin Information: Factions
[23:52:58 INFO]: - Version: 1.6.9.5-U0.1.10
[23:52:58 INFO]: - Author(s): Olof Larsson, Brett Flannigan, drtshock
[23:52:58 INFO]: - Status: Enabled
```

Initial Report: 
http://prntscr.com/54hx8b from yesterday  https://imgur.com/EikaRM3

```
Server.log https://gist.github.com/chamunks/f41343782d92e020c6d9
```

**Comment by drtshock** [comment] 2014-11-10 05:10
Duplicate of #120

**Closed as completed by drtshock** 2014-11-10 05:10 UTC
